const KEY_ENV = import.meta.env;
    

export const MOCKAPI_URL = KEY_ENV.VITE_MOCKAPI_URL
export const VECTORSHIFT_URL = KEY_ENV.VITE_VECTORSHIFT_URL
export const VECTORSHIFT_KEY = KEY_ENV.VITE_VECTORSHIFT_KEY